'use strict';
const {createHash}=require('node:crypto'),{keccak256,AbiCoder,concat}=require('ethers'),{decompress}=require('../optimization/scripts/lz4.cjs'),{recipe}=require('../scripts/recipes.cjs');
const {generatedName}=require('./names.cjs');
const HEADER="<svg xmlns='http://www.w3.org/2000/svg' width='420' height='420' viewBox='109.06 15.22 420 420'>";
function createArtReader({catalog,manifest}){
 const blob=Buffer.from(catalog);if(createHash('sha256').update(blob).digest('hex')!==manifest.blobSHA256||blob.subarray(0,4).toString()!=='PG06')throw Error('GENESIS_ART_CHANGED');
 const hashes=[];for(let i=0;i<blob.length;i+=24000)hashes.push(keccak256(concat(['0x00',blob.subarray(i,i+24000)])));
 if(keccak256(AbiCoder.defaultAbiCoder().encode(['uint256','bytes32[]'],[blob.length,hashes]))!==manifest.runtimeCommitment)throw Error('GENESIS_ART_CHANGED');
 const count=blob.readUInt16BE(4),td=blob.readUInt32BE(12),bd=blob.readUInt32BE(16),blocks=blob.readUInt16BE(6),literalStart=bd+blocks*12,cache=new Map(),dictionary=new Map();
 const slice=(a,n)=>{if(a<0||n<0||a+n>blob.length)throw Error('GENESIS_ART_BOUNDS');return blob.subarray(a,a+n);};
 function value(token){if(token>=count)throw Error('GENESIS_ART_TOKEN');const at=32+token*10,offset=blob.readUIntBE(at,3),length=blob.readUInt16BE(at+3);if(!(offset&0x800000))return slice(literalStart+offset,length);let cursor=offset&0x7fffff,left=length,pieces=[];while(left){const id=cursor>>>16;if(id>=blocks)throw Error('GENESIS_ART_BLOCK');if(!dictionary.has(id)){const a=bd+id*12;dictionary.set(id,decompress(slice(blob.readUInt32BE(a),blob.readUInt32BE(a+4)),blob.readUInt32BE(a+8)).out);}const d=dictionary.get(id),start=cursor%65536,n=Math.min(left,d.length-start);if(n<=0)throw Error('GENESIS_ART_BLOCK_BOUNDS');pieces.push(d.subarray(start,start+n));cursor+=n;left-=n;}return Buffer.concat(pieces);}
 function trait(index){if(!Number.isInteger(index)||index<0||index>=896)throw Error('GENESIS_ART_TRAIT');if(cache.has(index))return cache.get(index);const a=td+index*40,p=decompress(slice(blob.readUInt32BE(a),blob.readUInt32BE(a+4)),blob.readUInt32BE(a+8)*2).out,map=slice(blob.readUInt32BE(a+28),blob.readUInt32BE(a+32)),parts=[];const local=i=>{if(i*2+2>map.length)throw Error('GENESIS_ART_REFERENCE');return value(map.readUInt16BE(i*2));};for(let i=0;i<p.length;i+=2){const word=p.readUInt16BE(i);if(word&0x8000){parts.push(local(word&0x7fff));i+=2;parts.push(local(p.readUInt16BE(i)),Buffer.from("'"));}else parts.push(local(word));}const text=Buffer.concat(parts);if(text.length!==blob.readUInt32BE(a+12)||createHash('sha256').update(text).digest('hex')!==manifest.traits[index].canonicalSHA256)throw Error('GENESIS_ART_RECONSTRUCTION');cache.set(index,text.toString());if(cache.size>96)cache.delete(cache.keys().next().value);return text.toString();}
 function render(id,nameId=1n){const ids=recipe(id);const traits=ids.map(index=>{const offset=blob.readUInt32BE(td+index*40+36),n=blob.readUInt16BE(offset),label=JSON.parse(decodeURIComponent(slice(offset+2,n).toString()));return Object.freeze({index,category:label.trait_type,name:label.value});});const svg=HEADER+ids.map(i=>"<g style='isolation:isolate'>"+trait(i)+'</g>').join('')+'</svg>';return Object.freeze({recipeId:String(id),nameId:String(nameId),name:generatedName(nameId),svg,image:'data:image/svg+xml,'+encodeURIComponent(svg),svgSHA256:createHash('sha256').update(svg).digest('hex'),catalogCommitment:manifest.runtimeCommitment,traitIds:Object.freeze(ids),traits:Object.freeze(traits),dimensions:'420 × 420'});}
 return Object.freeze({render,trait});
}
module.exports={createArtReader,HEADER};
