'use strict';
// Dense, bijective recipe IDs for the final master. Public NFT IDs are separate.
const groups=require('./final-groups.json');
const order=['color','nebula','stars','spiral','dust','overlay','wings','base','body','spikes','teeth','jaw','eyes','top'];
function choose(n,k){if(k<0||k>n)return 0n;let r=1n;for(let i=1;i<=k;i++)r=r*BigInt(n-i+1)/BigInt(i);return r;}
function subsets(n){let r=0n;for(let k=0;k<=9;k++)r+=choose(n,k);return r;}
const STARS=subsets(groups.stars.length),OVERLAYS=subsets(groups.overlay.length);
const hoodie=new Set(groups.hoodie),hoodieSpikes=new Set(groups.hoodieSpikes);
const pairTops=[-1,...groups.hoodie,...groups.top.filter(t=>!hoodie.has(t))];
const pairs=[];for(const top of pairTops)for(const spikes of [-1,...groups.spikes])if(!hoodie.has(top)||spikes===-1||hoodieSpikes.has(spikes))pairs.push([spikes,top]);
const radices=[BigInt(groups.color.length),BigInt(1+groups.nebula.length+groups.spiral.length),STARS,BigInt(groups.dust.length+1),OVERLAYS,BigInt(groups.wings.length+1),BigInt(groups.base.length),BigInt(groups.body.length+1),BigInt(pairs.length),BigInt(groups.teeth.length+1),BigInt(groups.jaw.length),BigInt(groups.eyes.length)];
const TRAIT_COUNT=order.reduce((n,k)=>n+groups[k].length,0);if(TRAIT_COUNT!==896)throw Error('REVISION_TRAIT_COUNT');
const N=radices.reduce((a,b)=>a*b,1n);
function unrankSubset(rank,n){rank=BigInt(rank);if(rank<0||rank>=subsets(n))throw Error('SUBSET_BOUNDS');let k=0;while(rank>=choose(n,k)){rank-=choose(n,k);k++;}const out=[];let start=0;for(let left=k;left>0;left--){for(let j=start;j<n;j++){const count=choose(n-j-1,left-1);if(rank<count){out.push(j);start=j+1;break;}rank-=count;}}return out;}
function rankSubset(xs,n){if(xs.length>9||xs.some((x,i)=>!Number.isInteger(x)||x<0||x>=n||(i&&xs[i-1]>=x)))throw Error('SUBSET_INVALID');let r=0n;for(let k=0;k<xs.length;k++)r+=choose(n,k);let start=0;for(let i=0;i<xs.length;i++){for(let j=start;j<xs[i];j++)r+=choose(n-j-1,xs.length-i-1);start=xs[i]+1;}return r;}
function fields(id){id=BigInt(id);if(id<1n||id>N)throw Error('RECIPE_BOUNDS');let r=id-1n;return radices.map(n=>{const x=r%n;r/=n;return x;});}
function fromFields(xs){if(xs.length!==radices.length)throw Error('RECIPE_FIELDS');let rank=0n;for(let i=xs.length-1;i>=0;i--){const x=BigInt(xs[i]);if(x<0n||x>=radices[i])throw Error('RECIPE_FIELD');rank=rank*radices[i]+x;}return rank+1n;}
function recipe(id){const f=fields(id);const out=[];const required=(g,i)=>out.push(groups[g][Number(f[i])]);const optional=(g,i)=>{if(f[i])out.push(groups[g][Number(f[i]-1n)]);};required('color',0);if(f[1]>0n&&f[1]<=BigInt(groups.nebula.length))out.push(groups.nebula[Number(f[1]-1n)]);out.push(...unrankSubset(f[2],groups.stars.length).map(i=>groups.stars[i]));if(f[1]>BigInt(groups.nebula.length))out.push(groups.spiral[Number(f[1]-BigInt(groups.nebula.length+1))]);optional('dust',3);out.push(...unrankSubset(f[4],groups.overlay.length).map(i=>groups.overlay[i]));optional('wings',5);required('base',6);optional('body',7);const [spikes,top]=pairs[Number(f[8])];if(spikes>=0)out.push(spikes);optional('teeth',9);required('jaw',10);required('eyes',11);if(top>=0)out.push(top);return out;}
function validateSelection(ids){if(!Array.isArray(ids)||ids.length>29||ids.some(x=>!Number.isInteger(x)||x<0||x>=TRAIT_COUNT))throw Error('TRAIT_BOUNDS');const selected=Object.fromEntries(order.map(k=>[k,[]]));let prior=-1;for(const id of ids){const category=order.findIndex(k=>groups[k].includes(id));if(category<prior||category<0)throw Error('LAYER_ORDER');prior=category;selected[order[category]].push(id);}for(const k of order){const a=selected[k];if(['color','base','jaw','eyes'].includes(k)?a.length!==1:['stars','overlay'].includes(k)?a.length>9:a.length>1)throw Error('MULTIPLICITY');if(a.some((id,i)=>i&&a[i-1]>=id))throw Error('SOURCE_ORDER');}if(selected.nebula.length&&selected.spiral.length)throw Error('NEBULA_SPIRAL');if(selected.top.some(x=>hoodie.has(x))&&selected.spikes.some(x=>!hoodieSpikes.has(x)))throw Error('HOODIE_SPIKES');return selected;}
function encodeSelection(ids){const s=validateSelection(ids),idx=k=>groups[k].indexOf(s[k][0]),opt=k=>s[k].length?idx(k)+1:0;return fromFields([idx('color'),s.nebula.length?idx('nebula')+1:s.spiral.length?idx('spiral')+groups.nebula.length+1:0,rankSubset(s.stars.map(i=>groups.stars.indexOf(i)),groups.stars.length),opt('dust'),rankSubset(s.overlay.map(i=>groups.overlay.indexOf(i)),groups.overlay.length),opt('wings'),idx('base'),opt('body'),pairs.findIndex(([sp,t])=>sp===(s.spikes[0]??-1)&&t===(s.top[0]??-1)),opt('teeth'),idx('jaw'),idx('eyes')]);}
module.exports={groups,order,TRAIT_COUNT,pairs,radices,N,STARS,OVERLAYS,choose,subsets,rankSubset,unrankSubset,fields,fromFields,recipe,validateSelection,encodeSelection,recipeForRank:r=>recipe(BigInt(r)+1n),tokenForRank:r=>BigInt(r)+1n,A:1n,B:0n};
if(require.main===module)require('./generate-final-recipes.cjs').generate(module.exports);
