'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const {compress,decompress}=require('./lz4.cjs');
const sourceLock=require('../../owner-art/source-lock.json');
const ROOT=path.resolve(__dirname,'../../..'),OUT=path.join(__dirname,'../.generated');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const encode=s=>s.replace(/[^A-Za-z0-9\-._~!$&'()*+,;=:@/]/g,c=>'%25'+c.charCodeAt(0).toString(16).toUpperCase().padStart(2,'0'));
function compileCatalog(){
 cp.execFileSync('python3',[path.join(__dirname,'structural.py')],{stdio:'pipe'});
 const c=JSON.parse(fs.readFileSync(path.join(OUT,'dictionary-candidate.json')));
 if(c.tokens.length>=32768)throw Error('TOKEN_OPCODE_RANGE');
 const strings=[...new Set([...c.tokens,...c.tokens.map(encode)])].sort();
 if(strings.some(s=>Buffer.byteLength(s)!==s.length))throw Error('NON_ASCII_CATALOG');
 const short=strings.filter(s=>s.length<64).sort((a,b)=>b.length-a.length||(a<b?-1:a>b?1:0)),long=strings.filter(s=>s.length>=64).sort((a,b)=>a.length-b.length||(a<b?-1:a>b?1:0));
 let packed='';const literalOffsets=new Map();for(const s of short){let at=packed.indexOf(s);if(at<0){let overlap=Math.min(s.length-1,packed.length);while(overlap>0&&!packed.endsWith(s.slice(0,overlap)))overlap--;at=packed.length-overlap;packed+=s.slice(overlap);}literalOffsets.set(s,at);}const literal=Buffer.from(packed),lp=literal.length;
 let pos=0;const offsets=new Map(long.map(s=>{let n=pos;pos+=Buffer.byteLength(s);return[s,n]})),dictionary=Buffer.from(long.join(''));
 const blocks=[];for(let i=0;i<dictionary.length;i+=65536){let raw=dictionary.subarray(i,i+65536),data=compress(raw,32),stats=decompress(data,raw.length);if(!stats.out.equals(raw))throw Error('DICTIONARY_ROUNDTRIP');blocks.push({raw,data,ops:stats.ops,copies:stats.copies,extensionBytes:stats.extensionBytes});}
 const tokenTable=Buffer.alloc(c.tokens.length*10);
 c.tokens.forEach((s,i)=>{let e=encode(s);tokenTable.writeUIntBE((s.length<64?literalOffsets.get(s):offsets.get(s)+0x800000),i*10,3);tokenTable.writeUInt16BE(Buffer.byteLength(s),i*10+3);tokenTable.writeUIntBE((e.length<64?literalOffsets.get(e):offsets.get(e)+0x800000),i*10+5,3);tokenTable.writeUInt16BE(Buffer.byteLength(e),i*10+8);});
 const templates=[],templateIndex=new Map();
 const programs=c.programs.map(p=>{const references=[...new Set(p)],local=new Map(references.map((t,i)=>[t,i])),mapping=Buffer.alloc(references.length*2);references.forEach((v,i)=>mapping.writeUInt16BE(v,i*2));const words=[];for(let i=0;i<p.length;i++){if(/^ [A-Za-z:-]+='$/.test(c.tokens[p[i]])&&c.tokens[p[i+2]]==="'"){words.push(local.get(p[i])|0x8000,local.get(p[i+1]));i+=2}else words.push(local.get(p[i]));}let raw=Buffer.alloc(words.length*2);words.forEach((v,i)=>raw.writeUInt16BE(v,i*2));let data=compress(raw,8),stats=decompress(data,raw.length);if(!stats.out.equals(raw))throw Error('PROGRAM_ROUNDTRIP');const key=raw.toString('hex');if(!templateIndex.has(key)){templateIndex.set(key,templates.length);templates.push({raw,data})}return {raw,data,mapping,templateId:templateIndex.get(key),ops:stats.ops,copies:stats.copies,extensionBytes:stats.extensionBytes}});
 const source=c.programs.map(p=>Buffer.from(p.map(i=>c.tokens[i]).join(''))),encoded=c.programs.map(p=>Buffer.from(p.map(i=>encode(c.tokens[i])).join('')));
 const finalManifest=JSON.parse(fs.readFileSync(path.join(ROOT,'genesis/final-art/canonical-manifest.json')));
 const labels=finalManifest.traits.map(t=>Buffer.from('%7B%22trait_type%22:%22'+encodeURIComponent(t.category)+'%22,%22value%22:%22'+encodeURIComponent(t.sourceName)+'%22%7D'));
 const header=Buffer.alloc(32),td=Buffer.alloc(c.programs.length*40),bd=Buffer.alloc(blocks.length*12);
 header.write('PG06');header.writeUInt16BE(c.tokens.length,4);header.writeUInt16BE(blocks.length,6);header.writeUInt32BE(32,8);header.writeUInt32BE(32+tokenTable.length,12);header.writeUInt32BE(32+tokenTable.length+td.length,16);header.writeUInt32BE(dictionary.length,20);header.writeUInt32BE(lp,24);header.writeUInt32BE(40,28);
 let offset=32+tokenTable.length+td.length+bd.length+lp;
 templates.forEach(t=>{t.offset=offset;offset+=t.data.length});
 programs.forEach((p,i)=>{td.writeUInt32BE(templates[p.templateId].offset,i*40);td.writeUInt32BE(p.data.length,i*40+4);td.writeUInt32BE(p.raw.length/2,i*40+8);td.writeUInt32BE(source[i].length,i*40+12);td.writeUInt32BE(encoded[i].length,i*40+16);td.writeUInt32BE(c.programs[i].reduce((n,t)=>n+(c.tokens[t].length<64?0:1+Number((offsets.get(c.tokens[t])%65536)+Buffer.byteLength(c.tokens[t])>65536)),0),i*40+20);td.writeUInt32BE(c.programs[i].reduce((n,t)=>n+(encode(c.tokens[t]).length<64?0:1+Number((offsets.get(encode(c.tokens[t]))%65536)+Buffer.byteLength(encode(c.tokens[t]))>65536)),0),i*40+24);td.writeUInt32BE(offset,i*40+28);td.writeUInt32BE(p.mapping.length,i*40+32);td.writeUInt32BE(p.templateId,i*40+36);offset+=p.mapping.length;});
 blocks.forEach((p,i)=>{bd.writeUInt32BE(offset,i*12);bd.writeUInt32BE(p.data.length,i*12+4);bd.writeUInt32BE(p.raw.length,i*12+8);offset+=p.data.length;});
 const labelRecords=labels.map((b,i)=>{td.writeUInt32BE(offset,i*40+36);const len=Buffer.alloc(2);len.writeUInt16BE(b.length);offset+=2+b.length;return Buffer.concat([len,b]);});
 const blob=Buffer.concat([header,tokenTable,td,bd,literal,...templates.map(p=>p.data),...programs.map(p=>p.mapping),...blocks.map(p=>p.data),...labelRecords]),pages=[];for(let i=0;i<blob.length;i+=24000)pages.push(blob.subarray(i,i+24000));
 // Independently execute the serialized directory/program records before pinning
 // them. The on-chain interpreter may omit per-token checks only because its
 // constructor accepts this exact immutable code-hash commitment.
 const decodedDictionary=Buffer.concat(blocks.map(b=>decompress(b.data,b.raw.length).out));
 for(let i=0;i<c.programs.length;i++)for(let mode=0;mode<2;mode++){
  const p=decompress(blob.subarray(td.readUInt32BE(i*40),td.readUInt32BE(i*40)+td.readUInt32BE(i*40+4)),td.readUInt32BE(i*40+8)*2).out;
  const pieces=[];let nodeCount=0;const map=blob.subarray(td.readUInt32BE(i*40+28),td.readUInt32BE(i*40+28)+td.readUInt32BE(i*40+32));
  const value=localId=>{if(localId*2+2>map.length)throw Error('LOCAL_REFERENCE');const t=map.readUInt16BE(localId*2);if(t>=c.tokens.length)throw Error('TOKEN_RANGE');const at=t*10+mode*5,o=tokenTable.readUIntBE(at,3),n=tokenTable.readUInt16BE(at+3);const long=Boolean(o&0x800000),start=o&0x7fffff,storage=long?decodedDictionary:literal;if(start+n>storage.length)throw Error('TOKEN_BOUNDS');if(long)nodeCount+=1+Number(start%65536+n>65536);return storage.subarray(start,start+n)};
  for(let q=0;q<p.length;q+=2){let t=p.readUInt16BE(q);if(t&0x8000){const prefix=value(t&0x7fff);if(prefix.length>=64)throw Error('PREFIX_RANGE');pieces.push(prefix);q+=2;if(q>=p.length)throw Error('ATTRIBUTE_TRUNCATED');pieces.push(value(p.readUInt16BE(q)),Buffer.from("'"));}else pieces.push(value(t));}
  if(!Buffer.concat(pieces).equals(mode?encoded[i]:source[i])||nodeCount!==td.readUInt32BE(i*40+(mode?24:20)))throw Error('SERIALIZED_RECONSTRUCTION');
 }
 const sourceAssets=path.join(ROOT,'genesis/final-art/canonical-traits');

 if(c.sourceManifestSHA256!==sha(fs.readFileSync(path.join(ROOT,'genesis/final-art/canonical-manifest.json')))||c.sourceConcatenatedSHA256!==finalManifest.canonicalConcatenatedSHA256||finalManifest.masterSHA256!==sourceLock.masterSHA256||sha(fs.readFileSync(path.join(ROOT,'genesis/final-art/source/mainPhilLayers.svg')))!==sourceLock.masterSHA256||sha(fs.readFileSync(path.join(ROOT,'genesis/owner-art/variants.json')))!==sourceLock.variantsSHA256||sha(fs.readFileSync(path.join(ROOT,'genesis/final-art/canonical-manifest.json')))!==sourceLock.manifestSHA256)throw Error('SOURCE_PROVENANCE');
 const manifest={masterSHA256:finalManifest.masterSHA256,traitCount:c.programs.length,format:'PG06',literalPacking:'longest-first containment and suffix overlap; ASCII lexical tie-break',geometryOrdering:'length ascending, ASCII lexical tie-break',templates:templates.length,rawReferenceMapBytes:programs.reduce((n,p)=>n+p.mapping.length,0),literalBytes:lp,minDictionaryMatch:32,minProgramMatch:8,sourceManifestSHA256:c.sourceManifestSHA256,sourceConcatenatedSHA256:c.sourceConcatenatedSHA256,blobSHA256:sha(blob),catalogBytes:blob.length,dictionarySHA256:sha(dictionary),literalSHA256:sha(literal),tokenTableSHA256:sha(tokenTable),programFormat:'uint16 local reference, or uint16 (0x8000|local attribute prefix reference) followed by uint16 local value reference and implicit apostrophe; each trait supplies a uint16 global-token reference map',pages:pages.map((p,i)=>({index:i,bytes:p.length,sha256:sha(p)})),dictionaryBytes:dictionary.length,compressedDictionaryBytes:blocks.reduce((n,b)=>n+b.data.length,0),compressedProgramBytes:templates.reduce((n,b)=>n+b.data.length,0),tokenCount:c.tokens.length,blockStats:blocks.map(({raw,data,ops,copies,extensionBytes})=>({rawBytes:raw.length,compressedBytes:data.length,ops,copies,extensionBytes})),traits:c.sourcePaths.map((p,i)=>({index:i,path:p,programOffset:td.readUInt32BE(i*40),programWordCount:td.readUInt32BE(i*40+8),templateId:programs[i].templateId,labelOffset:td.readUInt32BE(i*40+36),referenceMapOffset:td.readUInt32BE(i*40+28),referenceMapBytes:td.readUInt32BE(i*40+32),rawCopyNodes:td.readUInt32BE(i*40+20),encodedCopyNodes:td.readUInt32BE(i*40+24),sourceSHA256:sha(fs.readFileSync(path.join(sourceAssets,p))),canonicalSHA256:sha(source[i]),encodedSHA256:sha(encoded[i]),svgBytes:source[i].length,encodedBytes:encoded[i].length,refs:c.programs[i].length,programCompressedBytes:programs[i].data.length,programOps:programs[i].ops,programCopies:programs[i].copies,programExtensionBytes:programs[i].extensionBytes}))};
 const ethers=require('ethers');const commitment=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(['uint256','bytes32[]'],[blob.length,pages.map(p=>ethers.keccak256(ethers.concat(['0x00',p])))]));
 manifest.runtimeCommitment=commitment;
 fs.writeFileSync(path.join(ROOT,'genesis/contracts/PhilGenesisArtCommitment.sol'),`// SPDX-License-Identifier: MIT\npragma solidity 0.8.27;\n// Generated by optimization/scripts/compile.cjs from the pinned owner-revision 896-trait master-derived manifest.\nlibrary PhilGenesisArtCommitment { bytes32 internal constant EXPECTED = ${commitment}; }\n`);
 fs.writeFileSync(path.join(OUT,'catalog.bin'),blob);fs.writeFileSync(path.join(__dirname,'../evidence/optimized-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
 return {blob,pages,source,encoded,paths:c.sourcePaths,manifest,tokens:c.tokens,programs:c.programs,tokenTable,blocks};
}
module.exports={compileCatalog,encode};if(require.main===module){let c=compileCatalog();console.log(JSON.stringify({bytes:c.blob.length,pages:c.pages.length,dict:c.manifest.compressedDictionaryBytes,program:c.manifest.compressedProgramBytes,hash:c.manifest.blobSHA256}));}
